In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
from collections import OrderedDict
import matplotlib.pyplot as plt
from IPython.display import display, HTML

import math
import re

In [2]:
data_dir = "/Users/peixuangao/Desktop/Sifter-pcap-parse/input_output/"
output_file = "deq_out.dat"

In [3]:
output_file = data_dir + output_file
col = ["pkt_size", "rank", "flow_id", "pkt_id"]
output_df = pd.read_csv(output_file, sep = ' ', header = None)

In [4]:
output_df.columns = col

In [5]:
#output_df

    pkt_size  rank  flow_id  pkt_id
0         64     1        0       0
1         64     2        2       0
2         64     3        4       0
3         64     4        6       0
4         64     5        8       0
5         64     6       10       0
6         64     7       12       0
7         64     8       14       0
8         64     9       16       0
9         64    10       18       0
10        64    11       20       0
11        64    12       22       0
12        64    13       24       0
13        64    14       26       0
14        64    15       28       0
15        64    16       30       0
16        64    16       33       0
17        64    17       31       0
18        64    18       29       0
19        64    19       27       0
20        64    20       25       0
21        64    21       23       0
22        64    22       21       0
23        64    23       19       0
24        64    24       17       0
25        64    25       15       0
26        64    26       13       0
27        64    27       11       0
28        64    28        9       0
29        64    29        7       0
30        64    30        5       0
31        64    31        3       1
32        64    32       32       0
33        64    32        1       0

In [8]:
prev_rank = 0
for index, row in output_df.iterrows():
    if prev_rank <= row['rank']:
        print('Correct')
    else:
        print('Inversion')
        print(row['rank'], row['flow_id'])

Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct